name: Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: b6da9421-787a-4215-9648-aa7f8ee638d3
          heroku_app_name: "front-nuri" #Must be unique in Heroku
          heroku_email: "melhaoui.abderrahmane@gmail.com"
          appdir: "front" # <- This will point to the api folder in your project
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: nuri-challenge-backend
          DOCKERFILE_DIRECTORY: "api"
          HEROKU_EMAIL: "melhaoui.abderrahmane@gmail.com"
          HEROKU_API_KEY: b6da9421-787a-4215-9648-aa7f8ee638d3
          DOCKERFILE_NAME: "Dockerfile"
          DOCKER_OPTIONS: "--no-cache --progress plain"
        run: |
          cd ${DOCKERFILE_DIRECTORY}
          echo ${HEROKU_API_KEY} | docker login \
            --username=${HEROKU_EMAIL} \
            registry.heroku.com \
            --password-stdin
          docker build \
            --file ${DOCKERFILE_NAME} \
            ${DOCKER_OPTIONS} \
            --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push web --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
