name: Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: b6da9421-787a-4215-9648-aa7f8ee638d3
          heroku_app_name: "challenge-nuri" 
          heroku_email: "melhaoui.abderrahmane@gmail.com"
          appdir: "front"
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: cd api && yarn
      - name: Run tests 
        run: cd api && yarn run test
  build-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: nuri-challenge-backend
          DOCKERFILE_DIRECTORY: "api"
          HEROKU_EMAIL: "melhaoui.abderrahmane@gmail.com"
          HEROKU_API_KEY: b6da9421-787a-4215-9648-aa7f8ee638d3
          DOCKERFILE_NAME: "Dockerfile"
          DOCKER_OPTIONS: "--no-cache --progress plain"
        run: |
          cd ${DOCKERFILE_DIRECTORY}
          echo ${HEROKU_API_KEY} | docker login \
            --username=${HEROKU_EMAIL} \
            registry.heroku.com \
            --password-stdin
          docker build \
            --file ${DOCKERFILE_NAME} \
            ${DOCKER_OPTIONS} \
            --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push web --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
